modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/MOAKIEE/AE2-Lightning-Tech/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/MOAKIEE/AE2-Lightning-Tech"
logoFile = "ae2lt.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jade"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "jei"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "advanced_ae"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "expatternprovider"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "appflux"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
