package com.moakiee.ae2lt.client.gui;

import java.lang.reflect.Field;
import java.util.Map;
import java.util.UUID;

import appeng.client.gui.Icon;
import appeng.client.gui.style.Color;
import appeng.client.gui.style.PaletteColor;
import appeng.client.gui.style.ScreenStyle;
import appeng.client.gui.widgets.AE2Button;
import appeng.client.gui.widgets.AETextField;
import appeng.client.gui.widgets.TabButton;

import com.moakiee.ae2lt.AE2LightningTech;
import com.moakiee.ae2lt.client.ClientFrequencyCache;
import com.moakiee.ae2lt.grid.FrequencyAccessLevel;
import com.moakiee.ae2lt.grid.FrequencySecurityLevel;
import com.moakiee.ae2lt.grid.WirelessFrequency;
import com.moakiee.ae2lt.menu.FrequencyMenu;
import com.moakiee.ae2lt.network.*;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.Tooltip;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.Style;
import net.minecraft.network.chat.TextColor;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Inventory;
import net.neoforged.neoforge.network.PacketDistributor;

/**
 * Multi-tab frequency management screen, modeled after Flux Networks' GUI.
 * Polls {@link ClientFrequencyCache#revision()} each frame and rebuilds
 * widgets when the server-pushed state changes.
 */
public class FrequencyScreen extends AbstractContainerScreen<FrequencyMenu> {

    private static final int GUI_WIDTH = 176;
    private static final int GUI_HEIGHT = 166;

    /**
     * AE2 {@link TabButton} renders at a fixed 22×22 size (see its
     * constructor bytecode). We expose these as named constants so the
     * rest of the screen can hit-test the same footprint.
     */
    private static final int TAB_WIDTH = 22;
    private static final int TAB_HEIGHT = 22;
    /**
     * Horizontal step between consecutive tab buttons (AE2 BOX tabs
     * already ship with their own 1-px inner border, so tabs can sit
     * flush — 22 px step with no extra gap looks correct, identical to
     * the terminal-style tab strip used by AE2's Pattern Access screens).
     */
    private static final int TAB_STEP = 22;
    private static final int ITEMS_PER_PAGE = 6;

    /**
     * AE2-styled background texture generated by
     * {@code examples/16_gui_wireless_overload_controller.py} in the
     * MinecraftImageHelper project. Texture is 256×256; the drawn content
     * occupies exactly (0,0)..(176,166) — a clean lavender chassis with
     * a 1-px AE2 bevel. The tab "ears" above {@code topPos} are rendered
     * by {@link TabButton} widgets themselves, so nothing is baked into
     * the background for the tab strip.
     */
    private static final ResourceLocation BACKGROUND_TEXTURE = ResourceLocation.fromNamespaceAndPath(
            AE2LightningTech.MODID, "textures/gui/wireless_overloaded_controller.png");
    private static final int TEXTURE_SIZE = 256;

    // AE2 standard text tones — matches AE2's own screens such as
    // terminal.png / craftingcpu.png where titles read as dark charcoal
    // on the light-lavender panel.
    private static final int AE2_TEXT_TITLE = 0x404040;
    private static final int AE2_TEXT_BODY  = 0x404040;
    private static final int AE2_TEXT_MUTED = 0x7F7F7F;

    // AE2 recessed-well palette — same tones AE2 uses on slot sprites and
    // recessed content panels. The well reads as a sunken shelf that the
    // {@link AETextField} / list rows sit inside.
    private static final int AE2_WELL_FILL     = 0xFFB4B4BF;
    private static final int AE2_WELL_SHADOW   = 0xFF5A5A6B; // top-left
    private static final int AE2_WELL_HILIGHT  = 0xFFFFFFFF; // bottom-right

    /**
     * AETextField's native {@code guis/text_field.png} frame is a fixed 12
     * px tall 3-slice. Creating the field at this exact height keeps the
     * AE2 frame flush with the recessed shelf we draw behind it.
     */
    private static final int INPUT_HEIGHT = 12;

    /**
     * Hard upper bound for {@link AETextField}'s width. AE2's
     * {@code text_field.png} 3-slice draws a 1-px left cap, a middle band
     * stretched up to {@code min(126, w-2)} pixels wide, and a 1-px right
     * cap at {@code x + w - 1}. Above 128 px the middle band caps at 126
     * and leaves a visible gap between it and the right cap — the exact
     * "empty bracket" artifact seen in the earlier build's Settings tab.
     * Anything at or below this width renders flush.
     */
    private static final int INPUT_MAX_WIDTH = 128;

    /**
     * Minimal {@link ScreenStyle} built once at class-load so
     * {@link AETextField} can look up its text / selection /
     * placeholder colours via {@link ScreenStyle#getColor(PaletteColor)}.
     * AE2 normally loads this from a JSON file attached to the screen;
     * we don't have one, so we seed the palette via reflection directly
     * on the private {@code palette} EnumMap populated by the
     * {@code ScreenStyle} no-arg constructor.
     */
    private static final ScreenStyle AE2_STYLE = buildAe2Style();

    @SuppressWarnings("unchecked")
    private static ScreenStyle buildAe2Style() {
        ScreenStyle style = new ScreenStyle();
        try {
            Field paletteField = ScreenStyle.class.getDeclaredField("palette");
            paletteField.setAccessible(true);
            Map<PaletteColor, Color> palette = (Map<PaletteColor, Color>) paletteField.get(style);
            // AE2 hex order is (a, r, g, b) via Color(r, g, b, a)
            palette.put(PaletteColor.DEFAULT_TEXT_COLOR,    new Color(0x40, 0x40, 0x40, 0xFF));
            palette.put(PaletteColor.MUTED_TEXT_COLOR,      new Color(0x7F, 0x7F, 0x7F, 0xFF));
            palette.put(PaletteColor.SELECTION_COLOR,       new Color(0x78, 0xAA, 0xFF, 0x78));
            // Text inside AETextField renders over the dark slate interior of
            // guis/text_field.png — dark-on-dark would be invisible, so we
            // match AE2's own Quartz Knife field and use near-white text.
            palette.put(PaletteColor.TEXTFIELD_TEXT,        new Color(0xFF, 0xFF, 0xFF, 0xFF));
            palette.put(PaletteColor.TEXTFIELD_PLACEHOLDER, new Color(0x60, 0x60, 0x60, 0xFF));
            palette.put(PaletteColor.TEXTFIELD_SELECTION,   new Color(0x78, 0xAA, 0xFF, 0x78));
            palette.put(PaletteColor.TEXTFIELD_ERROR,       new Color(0xC8, 0x46, 0x46, 0xFF));
            palette.put(PaletteColor.ERROR,                 new Color(0xC8, 0x46, 0x46, 0xFF));
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(
                    "Failed to populate AE2 ScreenStyle palette for FrequencyScreen", e);
        }
        return style;
    }

    private FrequencyNavigationTab currentTab = FrequencyNavigationTab.TAB_HOME;
    private int selectionPage = 0;
    private int memberPage = 0;
    private int connectionPage = 0;

    private AETextField nameField;
    private AETextField passwordField;
    private FrequencySecurityLevel editSecurity = FrequencySecurityLevel.PRIVATE;
    private int editColor = 0x1E90FF;

    private int lastCacheRevision = -1;
    private int lastFreqId = Integer.MIN_VALUE;

    // popup state for Members tab
    private UUID popupMemberUUID;
    private String popupMemberName = "";
    private FrequencyAccessLevel popupMemberAccess = FrequencyAccessLevel.USER;
    // When true, the popup target is an online player who isn't a member
    // yet. Only the "Set as User" action is meaningful — the other three
    // buttons are greyed out since there's nothing to demote or remove.
    private boolean popupIsStranger = false;

    /**
     * Last server-sent {@link FrequencyResponsePacket} message rendered
     * as an in-GUI toast. Minecraft's action-bar lives in the hotbar
     * zone — which container screens cover — so a raw
     * {@code displayClientMessage(..., true)} is invisible while this
     * GUI is open. Stashing the component here and painting it inside
     * {@link #renderLabels} makes the feedback actually reach the user.
     */
    private Component inlineError = null;
    private long inlineErrorExpiresAt = 0L;
    private static final long INLINE_ERROR_DURATION_MS = 4000L;

    /**
     * Called by {@link FrequencyResponsePacket}'s client handler when
     * this screen is the active one. Replaces whatever prior toast was
     * showing (a newer error always wins — the previous one is already
     * stale information after a fresh server round-trip).
     */
    public void showInlineError(Component message) {
        this.inlineError = message;
        this.inlineErrorExpiresAt = System.currentTimeMillis() + INLINE_ERROR_DURATION_MS;
    }

    // When true, the Settings-tab Delete button opened the confirmation
    // modal; the underlying tab body is suppressed and only
    // Confirm/Cancel are actionable. Cleared on tab switch and after
    // either button fires.
    private boolean deleteConfirmOpen = false;

    private static final int[] PRESET_COLORS = {
            0x6B17E8, 0x4400EC, 0x0033FF, 0x00ABFF, 0x00FFD9, 0x00FF00, 0x77FF00,
            0xFFFF00, 0xFF8800, 0xFF0000, 0xFF006A, 0xEC00EC, 0x7F7F7F, 0xFFFFFF
    };

    private FrequencyMenu freqMenu() { return getMenu(); }

    private int token() { return getMenu().containerId; }

    public FrequencyScreen(FrequencyMenu menu, Inventory playerInv, Component title) {
        super(menu, playerInv, title);
        this.imageWidth = GUI_WIDTH;
        this.imageHeight = GUI_HEIGHT;
    }

    @Override
    protected void init() {
        super.init();
        lastCacheRevision = ClientFrequencyCache.revision();
        lastFreqId = freqMenu().getCurrentFrequencyId();
        initTabWidgets();
    }

    @Override
    public void containerTick() {
        super.containerTick();
        int rev = ClientFrequencyCache.revision();
        int fid = freqMenu().getCurrentFrequencyId();
        if (rev != lastCacheRevision || fid != lastFreqId) {
            lastCacheRevision = rev;
            lastFreqId = fid;
            initTabWidgets();
        }
    }

    /**
     * Constructs an {@link AETextField} the same way AE2's own
     * {@code WidgetContainer.addTextField} does: after the constructor
     * it calls {@code setBordered(false)} so the inherited
     * {@link net.minecraft.client.gui.components.EditBox}'s default
     * 1-px light border and black interior fill are suppressed, leaving
     * AE2's {@code guis/text_field.png} 3-slice sprite as the ONLY
     * visible frame. Without this, EditBox's default black rectangle
     * sits inside AE2's sprite and produces the bracket-with-black-fill
     * artifact that was visible in the Settings and Create tabs.
     */
    private AETextField makeAe2Field(int x, int y, int width, int height) {
        AETextField field = new AETextField(AE2_STYLE, font, x, y, width, height);
        field.setBordered(false);
        return field;
    }

    /**
     * Placeholder string shown in the Settings-tab password field when
     * the frequency already has a stored (and now hashed) password. The
     * user can't see the real value — we only need a visual marker —
     * and any first keystroke/backspace clears it so they can type a
     * fresh password. Submitting without touching the field leaves the
     * sentinel in place, and the Apply handler sends {@code ""} to the
     * server (which preserves the stored hash).
     *
     * <p>Eight U+2022 bullets. Width stays under the 16-char
     * {@code MAX_PASSWORD_LENGTH} cap so it never gets truncated when
     * {@link AETextField#setValue} enforces the length limit.</p>
     */
    private static final String PASSWORD_SENTINEL = "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";

    /**
     * Tracks whether the Settings-tab password field is still showing
     * the {@link #PASSWORD_SENTINEL}. While armed, the Apply button
     * treats the field as "unchanged" and sends an empty string; once
     * the user types/deletes anything the flag flips off and the real
     * field value is forwarded verbatim.
     */
    private boolean settingsPasswordPristine = false;

    /**
     * When non-zero, a modal password prompt is active for this
     * frequency id — all tab body content is suppressed and the user
     * must either submit a password (triggering
     * {@link SelectFrequencyPacket} with the entered plaintext) or
     * cancel. Set by:
     * <ul>
     *   <li>{@link #checkAutoPasswordPrompt} — when the device we're
     *       looking at is bound to an ENCRYPTED frequency we're not a
     *       member of yet (case 1: right-click a locked device).</li>
     *   <li>The Selection-tab row {@code onPress} — when the player
     *       clicks an ENCRYPTED frequency they haven't unlocked yet
     *       (case 2: browsing the frequency list).</li>
     * </ul>
     * Cleared automatically on rebuild once the player's cache shows
     * them as a member (server-side {@code enrollAsUser} fires after
     * a successful {@link SelectFrequencyPacket} round-trip).
     */
    private int passwordPromptFreqId = 0;
    private String passwordPromptFreqName = "";
    /**
     * When {@code true}, cancelling the password prompt closes the
     * whole screen instead of just dismissing the popup. Used for the
     * device-bind path (case 1) where a non-member player who chickens
     * out has nothing else to do with the device anyway.
     */
    private boolean passwordPromptLocksScreen = false;
    private AETextField passwordPromptField;

    /**
     * Query string for the Selection-tab search field (repurposed from
     * the old inline password input). Matches frequency names
     * case-insensitively; empty means "show everything". Stored
     * outside {@link #initSelectionTab} so repeated rebuilds from
     * {@link #scheduleRebuild} don't reset it.
     */
    private String selectionSearchQuery = "";

    /**
     * {@link AETextField} that, while {@link #settingsPasswordPristine}
     * is true, wipes its placeholder on the first key or character
     * event so the user's typed input replaces the sentinel instead of
     * appending to it. Used only by the Settings tab — the Create tab's
     * password field never arms this flag and behaves as a plain field.
     */
    private final class PristinePasswordField extends AETextField {
        PristinePasswordField(int x, int y, int width, int height) {
            super(AE2_STYLE, font, x, y, width, height);
            setBordered(false);
        }

        @Override
        public boolean keyPressed(int key, int scan, int mods) {
            if (settingsPasswordPristine) {
                settingsPasswordPristine = false;
                setValue("");
            }
            return super.keyPressed(key, scan, mods);
        }

        @Override
        public boolean charTyped(char c, int mods) {
            if (settingsPasswordPristine) {
                settingsPasswordPristine = false;
                setValue("");
            }
            return super.charTyped(c, mods);
        }
    }

    private void initTabWidgets() {
        clearWidgets();
        closePopup();

        int x0 = leftPos;
        int y0 = topPos;

        buildTopTabs(x0, y0, false);

        // Password prompt re-evaluation: if the target frequency now
        // grants us membership (server accepted our password and
        // enrolled us as USER), auto-dismiss the popup. Otherwise,
        // seed the popup for the device-bind case — if the device
        // we opened is pinned to an ENCRYPTED frequency and we're
        // still an outsider, pop the prompt immediately so the user
        // doesn't see the locked GUI body.
        if (passwordPromptFreqId > 0) {
            var freq = ClientFrequencyCache.getFrequency(passwordPromptFreqId);
            if (freq == null || !needsPasswordUnlock(freq)) {
                passwordPromptFreqId = 0;
                passwordPromptLocksScreen = false;
            }
        }
        if (passwordPromptFreqId == 0) {
            checkAutoPasswordPrompt();
        }

        // Password prompt modal takes precedence over both the
        // delete-confirm modal and the normal tab body — the user
        // can't meaningfully interact with the selected frequency
        // until they authenticate.
        if (passwordPromptFreqId > 0) {
            buildPasswordPromptWidgets(x0, y0);
            return;
        }

        // Delete-confirm modal suppresses the current tab body so the
        // only clickable widgets (besides tab ears) are Confirm / Cancel.
        if (deleteConfirmOpen) {
            buildDeleteConfirmWidgets(x0, y0);
            return;
        }

        switch (currentTab) {
            case TAB_HOME -> initHomeTab(x0, y0);
            case TAB_SELECTION -> initSelectionTab(x0, y0);
            case TAB_CONNECTION -> initConnectionsTab(x0, y0);
            case TAB_MEMBER -> initMembersTab(x0, y0);
            case TAB_CREATE -> initCreateTab(x0, y0);
            case TAB_SETTING -> initSettingsTab(x0, y0);
        }
    }

    /**
     * Builds the Confirm / Cancel buttons for the delete-frequency modal.
     * The panel chrome is drawn in {@link #drawDeleteConfirmPanel}
     * (from {@code renderBg}), the title/hint text in
     * {@link #renderLabels}, and the two buttons live here so they stay
     * on top of the panel fill.
     */
    private void buildDeleteConfirmWidgets(int x0, int y0) {
        addRenderableWidget(new AE2Button(
                x0 + 22, y0 + 92, 58, 16,
                Component.translatable("ae2lt.gui.button.cancel"),
                btn -> { deleteConfirmOpen = false; scheduleRebuild(); }));

        addRenderableWidget(new AE2Button(
                x0 + 96, y0 + 92, 58, 16,
                Component.translatable("ae2lt.gui.button.confirm")
                        .copy().withStyle(ChatFormatting.DARK_RED),
                btn -> {
                    int freqId = freqMenu().getCurrentFrequencyId();
                    if (freqId > 0) {
                        PacketDistributor.sendToServer(new DeleteFrequencyPacket(token(), freqId));
                    }
                    deleteConfirmOpen = false;
                    switchTab(FrequencyNavigationTab.TAB_SELECTION);
                }));
    }

    /**
     * Returns true when the local player has no durable access to this
     * ENCRYPTED frequency and must type a password to unlock it.
     * Non-ENCRYPTED frequencies always return false (PRIVATE rejects
     * non-members outright; PUBLIC hands everyone a USER fallback).
     * Reads membership from {@link ClientFrequencyCache} — which is
     * synced by the server-push packets — so this check stays honest
     * even after a successful unlock (the enroll broadcast causes a
     * fresh rebuild, and needsPasswordUnlock flips to false).
     */
    private boolean needsPasswordUnlock(ClientFrequencyCache.CachedFrequency freq) {
        if (freq.security() != FrequencySecurityLevel.ENCRYPTED) return false;
        var mc = Minecraft.getInstance();
        if (mc.player == null) return false;
        UUID me = mc.player.getUUID();
        for (var m : ClientFrequencyCache.getMembers(freq.id())) {
            if (m.uuid().equals(me)) return false;
        }
        return true;
    }

    /**
     * Device-bind auto-prompt (case 1 from the password-gate UI spec):
     * if the device we just opened is pinned to a frequency that
     * requires password unlock for the current player, arm the popup
     * in lock-screen mode so Cancel closes the whole GUI instead of
     * just dismissing the modal.
     */
    private void checkAutoPasswordPrompt() {
        int currentId = freqMenu().getCurrentFrequencyId();
        if (currentId <= 0) return;
        var freq = ClientFrequencyCache.getFrequency(currentId);
        if (freq == null) return;
        if (needsPasswordUnlock(freq)) {
            passwordPromptFreqId = currentId;
            passwordPromptFreqName = freq.name();
            passwordPromptLocksScreen = true;
        }
    }

    /**
     * Builds the widgets for the password prompt modal: a single
     * {@link AETextField} centred below the freq name label plus a
     * Submit / Cancel button pair. Panel chrome is drawn in
     * {@link #drawPasswordPromptPanel} (from {@code renderBg}) and
     * the title text in {@link #renderLabels}.
     */
    private void buildPasswordPromptWidgets(int x0, int y0) {
        int fieldX = x0 + (imageWidth - INPUT_MAX_WIDTH) / 2;
        passwordPromptField = makeAe2Field(fieldX, y0 + 68, INPUT_MAX_WIDTH, INPUT_HEIGHT);
        passwordPromptField.setMaxLength(WirelessFrequency.MAX_PASSWORD_LENGTH);
        passwordPromptField.setPlaceholder(Component.translatable("ae2lt.gui.frequency.password"));
        addRenderableWidget(passwordPromptField);

        addRenderableWidget(new AE2Button(
                x0 + 22, y0 + 92, 58, 16,
                Component.translatable("ae2lt.gui.button.cancel"),
                btn -> cancelPasswordPrompt()));

        addRenderableWidget(new AE2Button(
                x0 + 96, y0 + 92, 58, 16,
                Component.translatable("ae2lt.gui.button.submit"),
                btn -> submitPasswordPrompt()));
    }

    /**
     * Fires the {@link SelectFrequencyPacket} with the typed password.
     * Does NOT clear {@link #passwordPromptFreqId} — the popup stays
     * open until the next rebuild re-evaluates
     * {@link #needsPasswordUnlock} against the updated cache. That
     * way a wrong password keeps the modal visible for retry (the
     * server's {@code NO_PERMISSION} response already renders as a
     * toast via {@link FrequencyResponsePacket}).
     */
    private void submitPasswordPrompt() {
        String pw = passwordPromptField == null ? "" : passwordPromptField.getValue();
        int freqId = passwordPromptFreqId;
        if (freqId <= 0) return;
        PacketDistributor.sendToServer(new SelectFrequencyPacket(
                token(), freqMenu().getBlockPos(), freqId, pw));
    }

    /**
     * Cancel button. For the device-bind path (case 1, flag
     * {@link #passwordPromptLocksScreen}) we have nothing useful to
     * show the player, so we close the whole screen. For the
     * selection-row path (case 2) we just dismiss the modal and
     * return to the Selection tab.
     */
    private void cancelPasswordPrompt() {
        boolean closeAll = passwordPromptLocksScreen;
        passwordPromptFreqId = 0;
        passwordPromptLocksScreen = false;
        if (closeAll) {
            Minecraft.getInstance().execute(this::onClose);
        } else {
            scheduleRebuild();
        }
    }

    /**
     * Rebuilds the six top {@link TabButton}s. Shared between the
     * default layout ({@link #initTabWidgets()}) and the member-edit
     * popup overlay ({@link #rebuildMemberPopupWidgets()}) so the tab
     * ear geometry stays identical in both views.
     *
     * @param popup when {@code true} the tab onPress closes the popup
     *              before switching tabs
     */
    private void buildTopTabs(int x0, int y0, boolean popup) {
        for (int i = 0; i < FrequencyNavigationTab.VALUES.length; i++) {
            FrequencyNavigationTab tab = FrequencyNavigationTab.VALUES[i];
            int bx = tabButtonX(x0, tab, i);
            int by = y0 - TAB_HEIGHT;

            Icon icon = iconFor(tab);
            ResourceLocation customIcon = customIconFor(tab);
            Component tooltip = Component.translatable(tab.getTranslationKey());
            Button.OnPress onPress = popup
                    ? btn -> { closePopup(); switchTab(tab); }
                    : btn -> switchTab(tab);

            HoverableTabButton button = new HoverableTabButton(icon, customIcon, tooltip, onPress);
            // BOX renders TAB_BUTTON_BACKGROUND — a fully-framed 22×22
            // sprite with a 1-px border on all four sides, matching AE2's
            // ME Interface / Pattern Access tab style. CORNER uses the
            // BORDERLESS variant which has no side frames, so adjacent
            // tabs read as one continuous strip rather than discrete
            // buttons (the effect reported as "tabs look like a long bar").
            button.setStyle(TabButton.Style.BOX);
            button.setX(bx);
            button.setY(by);
            button.setTooltip(Tooltip.create(tooltip));
            addRenderableWidget(button);
        }
    }

    /**
     * {@link TabButton} subclass that reports {@code isFocused() == true}
     * whenever the mouse is hovering over it. AE2's {@code renderWidget}
     * picks between {@code TAB_BUTTON_BACKGROUND} (default) and
     * {@code TAB_BUTTON_BACKGROUND_FOCUS} (cyan-filled) purely on
     * {@code isFocused()}, which vanilla MC only flips on keyboard focus.
     * Piggy-backing on the FOCUS sprite gives us the ME-Interface style
     * "hover fills the whole tab with light cyan" effect for free —
     * no custom overlay drawing needed, and the selected tab's appearance
     * is left unchanged (only the tab the mouse is over lights up).
     *
     * <p>Also supports a custom 16×16 icon overlay drawn on top of the
     * AE2 icon sprite. When {@code customIcon} is non-null the base AE2
     * {@link Icon} passed to super is treated as a placeholder — AE2 will
     * still blit it, but we paint our own texture directly on top at the
     * same (3, 3) offset used by the AE2 atlas icon.</p>
     */
    private static final class HoverableTabButton extends TabButton {
        private final ResourceLocation customIcon;

        HoverableTabButton(Icon icon, ResourceLocation customIcon,
                Component tooltip, Button.OnPress onPress) {
            super(icon, tooltip, onPress);
            this.customIcon = customIcon;
        }

        @Override
        public boolean isFocused() {
            return super.isFocused() || this.isHovered();
        }

        @Override
        public void renderWidget(GuiGraphics guiGraphics, int mouseX, int mouseY, float partialTick) {
            super.renderWidget(guiGraphics, mouseX, mouseY, partialTick);
            if (customIcon != null) {
                // AE2 TabButton paints its Icon at the top-left of the
                // 22×22 frame with a 3-px inset. Our PNGs are 16×16, so
                // overlaying at (x+3, y+3) fully covers the placeholder
                // Icon underneath and sits within the button's border.
                guiGraphics.blit(customIcon,
                        getX() + 3, getY() + 3,
                        0, 0, 16, 16, 16, 16);
            }
        }
    }

    /**
     * Fallback {@link Icon} from AE2's atlas — drawn underneath our
     * custom PNG overlay (if any). TAB_SETTING is the only tab that
     * reads this directly as the visible icon; the rest have a custom
     * PNG in {@link #customIconFor} that fully covers this sprite.
     */
    private static Icon iconFor(FrequencyNavigationTab tab) {
        return switch (tab) {
            case TAB_HOME       -> Icon.S_TERMINAL;
            case TAB_SELECTION  -> Icon.VIEW_MODE_ALL;
            case TAB_CONNECTION -> Icon.S_MACHINE;
            case TAB_MEMBER     -> Icon.ACCESS_READ_WRITE;
            case TAB_SETTING    -> Icon.COG;
            case TAB_CREATE     -> Icon.ENTER;
        };
    }

    /**
     * Custom 16×16 PNG overlay for each tab. Returns {@code null} when
     * the AE2 {@link Icon} from {@link #iconFor} should be the visible
     * sprite — currently only TAB_SETTING keeps the AE2 cog.
     */
    private static ResourceLocation customIconFor(FrequencyNavigationTab tab) {
        return switch (tab) {
            case TAB_HOME       -> TAB_ICON_HOME;
            case TAB_SELECTION  -> TAB_ICON_SELECTION;
            case TAB_CONNECTION -> TAB_ICON_CONNECTION;
            case TAB_MEMBER     -> TAB_ICON_MEMBER;
            case TAB_CREATE     -> TAB_ICON_CREATE;
            case TAB_SETTING    -> null;
        };
    }

    private static final ResourceLocation TAB_ICON_HOME = ResourceLocation.fromNamespaceAndPath(
            AE2LightningTech.MODID, "textures/gui/buttons/menu.png");
    private static final ResourceLocation TAB_ICON_SELECTION = ResourceLocation.fromNamespaceAndPath(
            AE2LightningTech.MODID, "textures/gui/buttons/frequency_select.png");
    private static final ResourceLocation TAB_ICON_CONNECTION = ResourceLocation.fromNamespaceAndPath(
            AE2LightningTech.MODID, "textures/gui/buttons/frequency_connect.png");
    private static final ResourceLocation TAB_ICON_MEMBER = ResourceLocation.fromNamespaceAndPath(
            AE2LightningTech.MODID, "textures/gui/buttons/frequency_member.png");
    private static final ResourceLocation TAB_ICON_CREATE = ResourceLocation.fromNamespaceAndPath(
            AE2LightningTech.MODID, "textures/gui/buttons/frequency_add.png");

    private void switchTab(FrequencyNavigationTab tab) {
        currentTab = tab;
        selectionPage = 0;
        memberPage = 0;
        connectionPage = 0;
        selectionSearchQuery = "";
        deleteConfirmOpen = false;
        scheduleRebuild();
    }

    /**
     * Defers {@link #initTabWidgets()} to the next main-thread tick so
     * the current click event (which is what brought us here via a
     * button's {@code onPress}) finishes dispatching BEFORE
     * {@link #clearWidgets} rips the clicked widget out of the screen's
     * children list. Rebuilding inline produced duplicate
     * {@code UI_BUTTON_CLICK} sounds on tab presses — almost certainly
     * a vanilla side-effect of replacing the widget that's still
     * unwinding its own {@code mouseClicked} stack frame.
     */
    private void scheduleRebuild() {
        Minecraft.getInstance().execute(this::initTabWidgets);
    }

    // Tab: Home

    private void initHomeTab(int x0, int y0) {
        addRenderableWidget(new AE2Button(
                x0 + 10, y0 + 130, 80, 16,
                Component.translatable("ae2lt.gui.button.disconnect"),
                btn -> PacketDistributor.sendToServer(
                        new SelectFrequencyPacket(token(), freqMenu().getBlockPos(), -1, ""))));
    }

    // Tab: Selection

    private void initSelectionTab(int x0, int y0) {
        // Search field (was the password field pre-popup-refactor).
        // Typed queries filter the frequency list by a
        // case-insensitive substring match on the name, rebuilding
        // the tab body on each keystroke so pagination and rows stay
        // in sync with the current filter.
        int searchX = x0 + (imageWidth - INPUT_MAX_WIDTH) / 2;
        AETextField searchField = makeAe2Field(searchX, y0 + 128, INPUT_MAX_WIDTH, INPUT_HEIGHT);
        searchField.setMaxLength(32);
        searchField.setValue(selectionSearchQuery);
        searchField.setResponder(value -> {
            if (!value.equals(selectionSearchQuery)) {
                selectionSearchQuery = value;
                selectionPage = 0;
                scheduleRebuild();
            }
        });
        searchField.setPlaceholder(Component.translatable("ae2lt.gui.frequency.search"));
        addRenderableWidget(searchField);

        var all = ClientFrequencyCache.getAllFrequenciesSorted();
        String q = selectionSearchQuery.trim().toLowerCase(java.util.Locale.ROOT);
        var freqs = q.isEmpty()
                ? all
                : all.stream()
                        .filter(f -> f.name().toLowerCase(java.util.Locale.ROOT).contains(q))
                        .toList();
        int totalPages = Math.max(1, (freqs.size() + ITEMS_PER_PAGE - 1) / ITEMS_PER_PAGE);
        selectionPage = Math.min(selectionPage, totalPages - 1);

        int start = selectionPage * ITEMS_PER_PAGE;
        int end = Math.min(start + ITEMS_PER_PAGE, freqs.size());

        for (int i = start; i < end; i++) {
            var f = freqs.get(i);
            int row = i - start;
            int by = y0 + 30 + row * 16;

            String label = switch (f.security()) {
                case ENCRYPTED -> f.name() + " [E]";
                case PRIVATE -> f.name() + " [P]";
                default -> f.name();
            };
            // Paint the frequency's stored RGB colour into the row
            // label — this is the colour the user picked in Create/Setting
            // and is the primary way to distinguish one frequency from
            // another at a glance. Without it every row shows up in
            // AE2Button's default near-white colour.
            Component display = Component.literal(label)
                    .setStyle(Style.EMPTY.withColor(TextColor.fromRgb(f.color() & 0xFFFFFF)));
            addRenderableWidget(new AE2Button(
                    x0 + 14, by, 148, 14,
                    display,
                    b -> {
                        // ENCRYPTED rows that the player can't unlock
                        // pop the password modal instead of firing a
                        // guaranteed-to-fail select — the modal
                        // round-trip handles authentication and the
                        // server's enrollAsUser then replays the rebuild
                        // with the player as a new USER member.
                        if (needsPasswordUnlock(f)) {
                            passwordPromptFreqId = f.id();
                            passwordPromptFreqName = f.name();
                            passwordPromptLocksScreen = false;
                            scheduleRebuild();
                        } else {
                            PacketDistributor.sendToServer(
                                    new SelectFrequencyPacket(token(), freqMenu().getBlockPos(), f.id(), ""));
                        }
                    }));
        }

        if (selectionPage > 0) {
            addRenderableWidget(new AE2Button(
                    x0 + 14, y0 + 148, 30, 14,
                    Component.literal("<<"),
                    btn -> { selectionPage--; scheduleRebuild(); }));
        }
        if (selectionPage < totalPages - 1) {
            addRenderableWidget(new AE2Button(
                    x0 + 132, y0 + 148, 30, 14,
                    Component.literal(">>"),
                    btn -> { selectionPage++; scheduleRebuild(); }));
        }
        // NOTE: no extra "Disconnect" button here — the Home tab already
        // owns the disconnect action. Duplicating it across tabs gives the
        // impression of the same widget being created twice.
    }

    // Tab: Connections

    private void initConnectionsTab(int x0, int y0) {
        int currentId = freqMenu().getCurrentFrequencyId();
        if (currentId <= 0) return;

        var conns = ClientFrequencyCache.getConnections(currentId);
        int totalPages = Math.max(1, (conns.size() + ITEMS_PER_PAGE - 1) / ITEMS_PER_PAGE);
        connectionPage = Math.min(connectionPage, totalPages - 1);

        if (connectionPage > 0) {
            addRenderableWidget(new AE2Button(
                    x0 + 14, y0 + 148, 30, 14,
                    Component.literal("<<"),
                    btn -> { connectionPage--; scheduleRebuild(); }));
        }
        if (connectionPage < totalPages - 1) {
            addRenderableWidget(new AE2Button(
                    x0 + 132, y0 + 148, 30, 14,
                    Component.literal(">>"),
                    btn -> { connectionPage++; scheduleRebuild(); }));
        }
    }

    // Tab: Members

    private void initMembersTab(int x0, int y0) {
        int currentId = freqMenu().getCurrentFrequencyId();
        if (currentId <= 0) return;

        var members = ClientFrequencyCache.getMembers(currentId);

        // Pull in every online player that isn't already a member and
        // expose them as "stranger" rows — clicking one lets an OWNER /
        // ADMIN add them as a USER. The tab/player list is already
        // synced by vanilla, so we read from the local connection.
        java.util.Set<UUID> memberIds = new java.util.HashSet<>();
        for (var m : members) memberIds.add(m.uuid());
        java.util.List<StrangerRow> strangers = new java.util.ArrayList<>();
        var connection = Minecraft.getInstance().getConnection();
        if (connection != null) {
            for (var info : connection.getOnlinePlayers()) {
                UUID id = info.getProfile().getId();
                if (id != null && !memberIds.contains(id)) {
                    strangers.add(new StrangerRow(id, info.getProfile().getName()));
                }
            }
            strangers.sort(java.util.Comparator.comparing(s -> s.name.toLowerCase()));
        }

        int totalRows = members.size() + strangers.size();
        int totalPages = Math.max(1, (totalRows + ITEMS_PER_PAGE - 1) / ITEMS_PER_PAGE);
        memberPage = Math.min(memberPage, totalPages - 1);

        int start = memberPage * ITEMS_PER_PAGE;
        int end = Math.min(start + ITEMS_PER_PAGE, totalRows);

        for (int i = start; i < end; i++) {
            int row = i - start;
            int by = y0 + 30 + row * 16;

            if (i < members.size()) {
                var m = members.get(i);
                // Build the member-row label as a SINGLE Component instance.
                // Earlier we used ``.copy().append(...)`` to splice a dimmed
                // " [O]" suffix onto the coloured name — but AE2Button's
                // horizontal-scroll text renderer interacts badly with
                // sibling Components (they can measure differently and end
                // up painting at staggered positions). A single literal with
                // a uniform style renders flush on one line inside the
                // 148×14 button sprite.
                StringBuilder text = new StringBuilder(m.name());
                if (isSelf(m.uuid())) {
                    text.append(' ')
                            .append(Component.translatable("ae2lt.gui.member.you").getString());
                }
                text.append(" [").append(accessShort(m.access())).append(']');
                Component display = Component.literal(text.toString())
                        .withStyle(m.access().getFormatting());
                // Self row is a read-only identity tag — every action
                // in the popup is self-locked anyway (see the multi-
                // owner self-lock rule), so disabling the click here
                // avoids surfacing a popup whose four buttons would
                // all be greyed out.
                AE2Button rowBtn = new AE2Button(
                        x0 + 14, by, 148, 14,
                        display,
                        b -> openMemberPopup(m.uuid(), m.name(), m.access()));
                if (isSelf(m.uuid())) {
                    rowBtn.active = false;
                }
                addRenderableWidget(rowBtn);
            } else {
                StrangerRow s = strangers.get(i - members.size());
                String shortCode = Component.translatable("ae2lt.gui.member.stranger_short").getString();
                Component display = Component.literal(s.name + " [" + shortCode + "]")
                        .withStyle(ChatFormatting.DARK_GRAY);
                addRenderableWidget(new AE2Button(
                        x0 + 14, by, 148, 14,
                        display,
                        b -> openStrangerPopup(s.uuid, s.name)));
            }
        }

        if (memberPage > 0) {
            addRenderableWidget(new AE2Button(
                    x0 + 14, y0 + 148, 30, 14,
                    Component.literal("<<"),
                    btn -> { memberPage--; scheduleRebuild(); }));
        }
        if (memberPage < totalPages - 1) {
            addRenderableWidget(new AE2Button(
                    x0 + 132, y0 + 148, 30, 14,
                    Component.literal(">>"),
                    btn -> { memberPage++; scheduleRebuild(); }));
        }
    }

    /** Simple holder for an online-but-not-a-member row in the Members tab. */
    private record StrangerRow(UUID uuid, String name) {}

    // Member edit popup

    private void openMemberPopup(UUID uuid, String name, FrequencyAccessLevel access) {
        popupMemberUUID = uuid;
        popupMemberName = name;
        popupMemberAccess = access;
        popupIsStranger = false;
        // Same deferral rationale as {@link #scheduleRebuild} — the
        // click that opens the popup is still unwinding when this runs.
        Minecraft.getInstance().execute(this::rebuildMemberPopupWidgets);
    }

    /**
     * Opens the popup for an online player who isn't a member yet.
     * Sets {@link #popupIsStranger} so {@link #rebuildMemberPopupWidgets}
     * knows to enable only the "Set as User" button — Set Admin / Remove
     * / Set Owner are meaningless for someone who has no access at all.
     * Clicking "Set as User" reuses the existing
     * {@code MEMBERSHIP_SET_USER} packet which creates the member when
     * none exists.
     */
    private void openStrangerPopup(UUID uuid, String name) {
        popupMemberUUID = uuid;
        popupMemberName = name;
        popupMemberAccess = FrequencyAccessLevel.USER;
        popupIsStranger = true;
        Minecraft.getInstance().execute(this::rebuildMemberPopupWidgets);
    }

    private void closePopup() {
        popupMemberUUID = null;
        popupIsStranger = false;
    }

    private void rebuildMemberPopupWidgets() {
        clearWidgets();
        int x0 = leftPos;
        int y0 = topPos;
        buildTopTabs(x0, y0, true);

        int px = x0 + 20;
        int py = y0 + 40;
        int pw = 136;

        FrequencyAccessLevel myAccess = selfAccess();
        FrequencyAccessLevel targetLevel = popupIsStranger
                ? FrequencyAccessLevel.BLOCKED
                : popupMemberAccess;
        boolean targetIsOwner = targetLevel == FrequencyAccessLevel.OWNER;
        // Self-lock (multi-owner): even though an OWNER can operate on
        // peer OWNERs, acting on yourself would drop the owner count,
        // breaking the "at least one OWNER remains" invariant. The
        // Members-tab row for self is already click-disabled, but this
        // keeps the popup safe if it's reached via another path.
        boolean isSelfTarget = !popupIsStranger && isSelf(popupMemberUUID);
        boolean ownerActingOnSelf = targetIsOwner && isSelfTarget;

        // Permission gates (shared rule from {@link
        // FrequencyAccessLevel#canActOnLevel}): evaluate max(current,
        // new) so promotions and demotions both route through the same
        // rank test. Strangers enter via {@code targetLevel = BLOCKED},
        // which means every rank-check behaves as if they had no prior
        // access — an OWNER can mint them straight into ADMIN or
        // OWNER without the artificial "USER first" stepping stone.
        // The text-style tint is applied only when the button is
        // actually clickable — otherwise the dark-red / gold colours
        // still read as active even on a greyed button.
        boolean canUser = !ownerActingOnSelf
                && targetLevel != FrequencyAccessLevel.USER
                && myAccess.canActOnLevel(FrequencyAccessLevel.higher(targetLevel, FrequencyAccessLevel.USER));
        AE2Button btnUser = new AE2Button(px, py, pw, 16,
                Component.translatable("ae2lt.gui.member.set_user"),
                btn -> sendMember(WirelessFrequency.MEMBERSHIP_SET_USER));
        btnUser.active = canUser;
        addRenderableWidget(btnUser);

        boolean canAdmin = !ownerActingOnSelf
                && targetLevel != FrequencyAccessLevel.ADMIN
                && myAccess.canActOnLevel(FrequencyAccessLevel.higher(targetLevel, FrequencyAccessLevel.ADMIN));
        AE2Button btnAdmin = new AE2Button(px, py + 20, pw, 16,
                Component.translatable("ae2lt.gui.member.set_admin"),
                btn -> sendMember(WirelessFrequency.MEMBERSHIP_SET_ADMIN));
        btnAdmin.active = canAdmin;
        addRenderableWidget(btnAdmin);

        // Remove is the one button that stays off for strangers —
        // there's no durable membership entry to cancel.
        boolean canRemove = !ownerActingOnSelf
                && !popupIsStranger
                && myAccess.canActOnLevel(targetLevel);
        Component removeLabel = Component.translatable("ae2lt.gui.member.remove");
        if (canRemove) {
            removeLabel = removeLabel.copy().withStyle(ChatFormatting.DARK_RED);
        }
        AE2Button btnRemove = new AE2Button(px, py + 40, pw, 16,
                removeLabel,
                btn -> sendMember(WirelessFrequency.MEMBERSHIP_CANCEL));
        btnRemove.active = canRemove;
        addRenderableWidget(btnRemove);

        // Renamed from "Transfer Ownership" now that we're multi-owner:
        // this promotes the target to OWNER without demoting existing
        // ones. Requires OWNER-rank reach (same-rank-by-owner rule).
        // The gold tint only lights up when the button is clickable.
        boolean canSetOwner = !targetIsOwner
                && myAccess.canActOnLevel(FrequencyAccessLevel.OWNER);
        Component setOwnerLabel = Component.translatable("ae2lt.gui.member.set_owner");
        if (canSetOwner) {
            setOwnerLabel = setOwnerLabel.copy().withStyle(ChatFormatting.GOLD);
        }
        AE2Button btnSetOwner = new AE2Button(px, py + 60, pw, 16,
                setOwnerLabel,
                btn -> sendMember(WirelessFrequency.MEMBERSHIP_TRANSFER_OWNERSHIP));
        btnSetOwner.active = canSetOwner;
        addRenderableWidget(btnSetOwner);

        addRenderableWidget(new AE2Button(px + 36, py + 84, 64, 16,
                Component.translatable("ae2lt.gui.button.cancel"),
                btn -> { closePopup(); scheduleRebuild(); }));
    }

    private void sendMember(byte type) {
        int currentId = freqMenu().getCurrentFrequencyId();
        if (currentId <= 0 || popupMemberUUID == null) return;
        PacketDistributor.sendToServer(new ChangeMemberPacket(token(), currentId, popupMemberUUID, type));
        closePopup();
        scheduleRebuild();
    }

    // Tab: Create

    private void initCreateTab(int x0, int y0) {
        int fieldX = x0 + (imageWidth - INPUT_MAX_WIDTH) / 2;
        nameField = makeAe2Field(fieldX, y0 + 30, INPUT_MAX_WIDTH, INPUT_HEIGHT);
        nameField.setMaxLength(WirelessFrequency.MAX_NAME_LENGTH);
        nameField.setPlaceholder(Component.translatable("ae2lt.gui.frequency.name"));
        addRenderableWidget(nameField);

        passwordField = makeAe2Field(fieldX, y0 + 68, INPUT_MAX_WIDTH, INPUT_HEIGHT);
        passwordField.setMaxLength(WirelessFrequency.MAX_PASSWORD_LENGTH);
        passwordField.setPlaceholder(Component.translatable("ae2lt.gui.frequency.password"));
        passwordField.setVisible(editSecurity == FrequencySecurityLevel.ENCRYPTED);
        addRenderableWidget(passwordField);

        addRenderableWidget(new AE2Button(
                x0 + 70, y0 + 50, 80, 14,
                getSecurityLabel(editSecurity),
                btn -> {
                    editSecurity = FrequencySecurityLevel.VALUES[
                            (editSecurity.ordinal() + 1) % FrequencySecurityLevel.VALUES.length];
                    passwordField.setVisible(editSecurity == FrequencySecurityLevel.ENCRYPTED);
                    btn.setMessage(getSecurityLabel(editSecurity));
                }));

        // Colour swatches stay as plain vanilla ``Button`` instances —
        // they're 14×14 solid-colour cells with no text, which neither
        // ``AE2Button`` nor ``TabButton`` can render. ``renderCreateLabels``
        // paints the actual colour over each swatch's rectangle.
        for (int i = 0; i < PRESET_COLORS.length; i++) {
            final int c = PRESET_COLORS[i];
            int cx = x0 + 48 + (i % 7) * 16;
            int cy = y0 + 90 + (i / 7) * 16;
            addRenderableWidget(Button.builder(Component.literal(" "),
                            btn -> editColor = c)
                    .bounds(cx, cy, 14, 14).build());
        }

        addRenderableWidget(new AE2Button(
                x0 + 64, y0 + 140, 48, 16,
                Component.translatable("ae2lt.gui.button.create"),
                btn -> {
                    if (nameField.getValue().isBlank()) return;
                    PacketDistributor.sendToServer(new CreateFrequencyPacket(
                            token(),
                            nameField.getValue(), editColor, editSecurity,
                            passwordField.getValue()));
                    switchTab(FrequencyNavigationTab.TAB_SELECTION);
                }));
    }

    // Tab: Settings

    private void initSettingsTab(int x0, int y0) {
        var freq = ClientFrequencyCache.getFrequency(freqMenu().getCurrentFrequencyId());
        if (freq == null) return;

        // Per-access-level layout: OWNERs see Delete+Apply, ADMINs see
        // Leave+Apply (they can edit but not destroy the frequency),
        // USERs see Leave only and all inputs render view-only. The
        // server-side self-leave branch (MEMBERSHIP_CANCEL) is how
        // non-editors bail out of a frequency they joined via
        // enrollAsUser or an admin-added USER slot.
        boolean isManager = hasManagerAccess();
        boolean isOwner = hasOwnerAccess();

        editSecurity = freq.security();
        editColor = freq.color();

        int fieldX = x0 + (imageWidth - INPUT_MAX_WIDTH) / 2;
        nameField = makeAe2Field(fieldX, y0 + 30, INPUT_MAX_WIDTH, INPUT_HEIGHT);
        nameField.setMaxLength(WirelessFrequency.MAX_NAME_LENGTH);
        nameField.setPlaceholder(Component.translatable("ae2lt.gui.frequency.name"));
        nameField.setValue(freq.name());
        nameField.setEditable(isManager);
        addRenderableWidget(nameField);

        // Settings tab uses the pristine-clearing subclass: when the
        // frequency is already ENCRYPTED we pre-fill the sentinel dots
        // so the user sees "a password is set here" without us leaking
        // the hash, and any keystroke wipes the sentinel so typed input
        // replaces it rather than appending. See
        // {@link #PASSWORD_SENTINEL}.
        passwordField = new PristinePasswordField(fieldX, y0 + 68, INPUT_MAX_WIDTH, INPUT_HEIGHT);
        passwordField.setMaxLength(WirelessFrequency.MAX_PASSWORD_LENGTH);
        passwordField.setPlaceholder(Component.translatable("ae2lt.gui.frequency.password"));
        passwordField.setVisible(editSecurity == FrequencySecurityLevel.ENCRYPTED);
        if (editSecurity == FrequencySecurityLevel.ENCRYPTED) {
            passwordField.setValue(PASSWORD_SENTINEL);
            settingsPasswordPristine = true;
        } else {
            settingsPasswordPristine = false;
        }
        // Password and security are OWNER-gated on the server
        // (EditFrequencyPacket bounces ADMIN with NO_PERMISSION when
        // either changes). Mirror that here so ADMIN doesn't hit a
        // "silent" Apply-failure by cycling the security button —
        // only isOwner gets to flip these.
        passwordField.setEditable(isOwner);
        addRenderableWidget(passwordField);

        AE2Button securityBtn = new AE2Button(
                x0 + 70, y0 + 50, 80, 14,
                getSecurityLabel(editSecurity),
                btn -> {
                    editSecurity = FrequencySecurityLevel.VALUES[
                            (editSecurity.ordinal() + 1) % FrequencySecurityLevel.VALUES.length];
                    passwordField.setVisible(editSecurity == FrequencySecurityLevel.ENCRYPTED);
                    // Cycling the security mode restarts password entry —
                    // the sentinel only makes sense on the very first
                    // render for an already-ENCRYPTED frequency, never
                    // after the user touches the security toggle.
                    passwordField.setValue("");
                    settingsPasswordPristine = false;
                    btn.setMessage(getSecurityLabel(editSecurity));
                });
        securityBtn.active = isOwner;
        addRenderableWidget(securityBtn);

        AE2Button applyBtn = new AE2Button(
                x0 + 96, y0 + 140, 48, 16,
                Component.translatable("ae2lt.gui.button.apply"),
                btn -> {
                    // If the sentinel is still in the field, the user
                    // didn't touch the password — forward an empty
                    // string so the server preserves the stored hash
                    // (see EditFrequencyPacket's "only overwrite when
                    // the payload is non-empty" branch).
                    String pw = settingsPasswordPristine ? "" : passwordField.getValue();
                    PacketDistributor.sendToServer(new EditFrequencyPacket(
                            token(),
                            freq.id(), nameField.getValue(), editColor,
                            editSecurity, pw));
                });
        applyBtn.active = isManager;
        addRenderableWidget(applyBtn);

        if (isOwner) {
            addRenderableWidget(new AE2Button(
                    x0 + 32, y0 + 140, 48, 16,
                    Component.translatable("ae2lt.gui.button.delete")
                            .copy().withStyle(ChatFormatting.DARK_RED),
                    btn -> { deleteConfirmOpen = true; scheduleRebuild(); }));
        } else {
            // Leave button: self-cancel via the membership packet.
            // Works for both ADMIN and USER because the server-side
            // MEMBERSHIP_CANCEL case allows self-targets regardless
            // of canEdit (only the self-lock on the last OWNER still
            // blocks). We disconnect the device FIRST (while we
            // still have member-level access on the current freq)
            // and then leave — once we're out of the members map
            // the server's disconnect access gate would reject us.
            addRenderableWidget(new AE2Button(
                    x0 + 32, y0 + 140, 48, 16,
                    Component.translatable("ae2lt.gui.button.leave")
                            .copy().withStyle(ChatFormatting.DARK_GRAY),
                    btn -> {
                        var mc = Minecraft.getInstance();
                        if (mc.player == null) return;
                        PacketDistributor.sendToServer(new SelectFrequencyPacket(
                                token(), freqMenu().getBlockPos(), -1, ""));
                        PacketDistributor.sendToServer(new ChangeMemberPacket(
                                token(), freq.id(), mc.player.getUUID(),
                                WirelessFrequency.MEMBERSHIP_CANCEL));
                        switchTab(FrequencyNavigationTab.TAB_SELECTION);
                    }));
        }
    }

    // Rendering

    @Override
    protected void renderBg(GuiGraphics g, float partialTick, int mouseX, int mouseY) {
        // Clean 176×166 AE2 chassis. The six top tab ears are drawn by
        // TabButton widgets themselves (AE2's ``TAB_BUTTON_BACKGROUND``
        // sprite), and the active-tab cyan halo is painted in
        // {@link #renderLabels} so it overlays the TabButton sprite
        // instead of being hidden beneath it.
        g.blit(
                BACKGROUND_TEXTURE,
                leftPos,
                topPos,
                0, 0,
                GUI_WIDTH,
                GUI_HEIGHT,
                TEXTURE_SIZE,
                TEXTURE_SIZE);

        // Per-tab recessed "shelves" — drawn BEFORE widgets so buttons
        // and text inputs sit on top of them. Mirrors the wide blue-gray
        // input rail that AE2's Crystal Cutter / similar terminals use
        // to visually anchor their content.
        renderTabShelves(g);

        // Member-edit popup panel background. This MUST be drawn from
        // {@link #renderBg} (before widgets render) — if drawn from
        // {@link #renderLabels} it overlays the popup buttons and hides
        // them. The corresponding text (member name / access short code)
        // is rendered later in {@link #renderLabels}, which is fine
        // because that text sits above the buttons rather than overlapping.
        if (popupMemberUUID != null) {
            drawMemberPopupPanel(g);
        }
        if (deleteConfirmOpen) {
            drawDeleteConfirmPanel(g);
        }
        if (passwordPromptFreqId > 0) {
            drawPasswordPromptPanel(g);
        }
    }

    /**
     * Same lavender chassis as {@link #drawDeleteConfirmPanel}, sized
     * to house the password prompt: title at top, a 12-px text field
     * just below, and a Cancel/Submit row. Kept separate so the delete
     * modal and password modal each own their own footprint.
     */
    private void drawPasswordPromptPanel(GuiGraphics g) {
        int px0 = leftPos + 16;
        int py0 = topPos + 50;
        int pw = 144;
        int ph = 66;
        g.fill(px0, py0, px0 + pw, py0 + ph, 0xFFCBCCD4);             // panel fill
        g.fill(px0, py0, px0 + pw, py0 + 1, 0xFF5A5A6B);               // top shadow
        g.fill(px0, py0, px0 + 1, py0 + ph, 0xFF5A5A6B);               // left shadow
        g.fill(px0 + pw - 1, py0, px0 + pw, py0 + ph, 0xFFFFFFFF);     // right highlight
        g.fill(px0, py0 + ph - 1, px0 + pw, py0 + ph, 0xFFFFFFFF);     // bottom highlight
    }

    /**
     * Draws the smaller delete-confirm modal panel. Same lavender
     * chassis + 1-px AE2 bevel as the member popup, sized to fit a
     * title line, a hint line, and a single row of Confirm/Cancel
     * buttons without crowding the Settings tab chrome above.
     */
    private void drawDeleteConfirmPanel(GuiGraphics g) {
        int px0 = leftPos + 16;
        int py0 = topPos + 50;
        int pw = 144;
        int ph = 66;
        g.fill(px0, py0, px0 + pw, py0 + ph, 0xFFCBCCD4);             // panel fill
        g.fill(px0, py0, px0 + pw, py0 + 1, 0xFF5A5A6B);               // top shadow
        g.fill(px0, py0, px0 + 1, py0 + ph, 0xFF5A5A6B);               // left shadow
        g.fill(px0 + pw - 1, py0, px0 + pw, py0 + ph, 0xFFFFFFFF);     // right highlight
        g.fill(px0, py0 + ph - 1, px0 + pw, py0 + ph, 0xFFFFFFFF);     // bottom highlight
    }

    /**
     * Draws the light-lavender popup panel with an AE2 1-px bevel in
     * screen coordinates. Kept separate from the text-layer content in
     * {@link #renderLabels} so buttons added by
     * {@link #rebuildMemberPopupWidgets()} sit on top of this panel
     * instead of being occluded by it.
     */
    private void drawMemberPopupPanel(GuiGraphics g) {
        int px0 = leftPos + 10;
        int py0 = topPos + 26;
        int pw = 156;
        // 120 rather than 110 so the Cancel button (local y=124..140)
        // sits inside the panel — at 110 it poked 4 px below the
        // bottom bevel.
        int ph = 120;
        g.fill(px0, py0, px0 + pw, py0 + ph, 0xFFCBCCD4);             // panel fill
        g.fill(px0, py0, px0 + pw, py0 + 1, 0xFF5A5A6B);               // top shadow
        g.fill(px0, py0, px0 + 1, py0 + ph, 0xFF5A5A6B);               // left shadow
        g.fill(px0 + pw - 1, py0, px0 + pw, py0 + ph, 0xFFFFFFFF);     // right highlight
        g.fill(px0, py0 + ph - 1, px0 + pw, py0 + ph, 0xFFFFFFFF);     // bottom highlight
    }

    /**
     * Draws the AE2-style recessed content shelf(es) for the current
     * tab. All coordinates here are screen-space, since this runs in
     * {@link #renderBg} before the pose is translated to the GUI local
     * frame by {@link AbstractContainerScreen}.
     */
    private void renderTabShelves(GuiGraphics g) {
        int x0 = leftPos;
        int y0 = topPos;
        switch (currentTab) {
            case TAB_HOME -> drawRecessedWell(g, x0 + 7, y0 + 20, imageWidth - 14, 72);
            case TAB_SELECTION, TAB_CONNECTION, TAB_MEMBER ->
                drawRecessedWell(g, x0 + 7, y0 + 28, imageWidth - 14, 96);
            default -> { /* create + setting have per-widget frames */ }
        }
    }

    /**
     * Draws an AE2-style recessed "shelf" frame — a sunken rectangle
     * with a 1-px dark top-left shadow and 1-px light bottom-right
     * highlight, blue-gray fill inside. Matches the visual grammar used
     * by AE2's slot wells and input rails.
     *
     * <p>All coordinates are LOCAL to the GUI (already translated to
     * {@code leftPos/topPos}); callers in {@link #renderBg} must use
     * screen coordinates directly instead (this method isn't called
     * from there).</p>
     */
    private void drawRecessedWell(GuiGraphics g, int x, int y, int w, int h) {
        g.fill(x, y, x + w, y + h, AE2_WELL_FILL);
        g.fill(x,         y,          x + w,     y + 1,      AE2_WELL_SHADOW);   // top
        g.fill(x,         y,          x + 1,     y + h,      AE2_WELL_SHADOW);   // left
        g.fill(x + w - 1, y,          x + w,     y + h,      AE2_WELL_HILIGHT);  // right
        g.fill(x,         y + h - 1,  x + w,     y + h,      AE2_WELL_HILIGHT);  // bottom
    }

    /**
     * Returns the screen-space x of a given tab button so the layout
     * never gets out of sync between {@link #buildTopTabs(int, int, boolean)}
     * and {@link #renderBg}. Five flush tabs span x=8..118 (22×5) and
     * the "Create" tab is right-anchored with a 2-px gap to the panel
     * edge at x=152..174, leaving a visible gap that reads as a small
     * breather between the "navigate" and "author" tab clusters.
     */
    private static int tabButtonX(int originX, FrequencyNavigationTab tab, int index) {
        if (tab == FrequencyNavigationTab.TAB_CREATE) {
            return originX + GUI_WIDTH - TAB_WIDTH - 2;
        }
        return originX + 8 + index * TAB_STEP;
    }

    @Override
    protected void renderLabels(GuiGraphics g, int mouseX, int mouseY) {
        drawFlatCentered(g,
                Component.translatable(currentTab.getTranslationKey()),
                imageWidth / 2, 6, AE2_TEXT_TITLE);

        // When the member-edit popup or delete-confirm modal is open it
        // covers the tab body — rendering the tab's labels underneath
        // leaks them through around the panel edges and creates a
        // cluttered look. Suppress the body labels while a modal is
        // active; the modal owns the visible surface until the user
        // cancels or commits.
        if (popupMemberUUID == null && !deleteConfirmOpen && passwordPromptFreqId == 0) {
            switch (currentTab) {
                case TAB_HOME -> renderHomeLabels(g);
                case TAB_SELECTION -> renderSelectionLabels(g);
                case TAB_CONNECTION -> renderConnectionLabels(g);
                case TAB_MEMBER -> renderMemberLabels(g);
                case TAB_CREATE -> renderCreateLabels(g);
                case TAB_SETTING -> renderSettingLabels(g);
            }
        }

        if (deleteConfirmOpen) {
            // Delete-confirm modal contents. Panel sits at local y=50..116
            // (from {@link #drawDeleteConfirmPanel}); title + hint go in
            // the 42 px head area above the Confirm/Cancel row (y=92..108).
            drawFlatCentered(g,
                    Component.translatable("ae2lt.gui.delete_confirm.title")
                            .copy().withStyle(ChatFormatting.DARK_RED),
                    imageWidth / 2, 60, AE2_TEXT_TITLE);
            drawFlatCentered(g,
                    Component.translatable("ae2lt.gui.delete_confirm.hint"),
                    imageWidth / 2, 74, AE2_TEXT_MUTED);
        }

        if (passwordPromptFreqId > 0) {
            // Password prompt modal contents. Panel sits at local y=50..116
            // (same footprint as the delete modal); header above the
            // text field at y=68 and Cancel/Submit at y=92.
            drawFlatCentered(g,
                    Component.translatable("ae2lt.gui.password_prompt.title", passwordPromptFreqName),
                    imageWidth / 2, 58, AE2_TEXT_TITLE);
        }

        if (popupMemberUUID != null) {
            // Header inside the popup panel: target member's name with
            // their access code tacked on as a single line, positioned
            // in the 14 px strip between the panel top (y=26) and the
            // first action button (y=40) so it never overlaps the
            // {@code 设为用户} row.
            // Stranger popup shows the target dimmed (they have no
            // access yet) with the localised "stranger" code tagged on
            // — everything else is the same one-line header layout so
            // the button stack below stays aligned.
            Component header;
            if (popupIsStranger) {
                String code = Component.translatable("ae2lt.gui.member.stranger_short").getString();
                header = Component.literal(popupMemberName + " [" + code + "]")
                        .withStyle(ChatFormatting.DARK_GRAY);
            } else {
                header = Component.literal(popupMemberName)
                        .withStyle(popupMemberAccess.getFormatting())
                        .copy()
                        .append(Component.literal(" [" + accessShort(popupMemberAccess) + "]")
                                .withStyle(ChatFormatting.DARK_GRAY));
            }
            drawFlatCentered(g, header, imageWidth / 2, 30, AE2_TEXT_TITLE);
        }

        // Hover feedback for the tab strip is handled natively by
        // {@link HoverableTabButton}, which flips AE2's BOX TabButton to
        // its FOCUS sprite whenever the mouse is over it. Nothing to
        // overlay here — the selected tab is identified by the GUI body
        // it opens, not by a border accent.

        // Inline error toast (server-pushed). Painted last so it sits
        // on top of every modal + tab body, near the bottom edge of
        // the panel where it doesn't collide with the primary
        // content. A dark translucent bar behind the text keeps it
        // legible on top of the recessed shelf + list rows.
        if (inlineError != null) {
            if (System.currentTimeMillis() < inlineErrorExpiresAt) {
                int textW = font.width(inlineError);
                int bgW = Math.min(imageWidth - 8, textW + 8);
                int bgX = (imageWidth - bgW) / 2;
                int bgY = imageHeight - 14;
                g.fill(bgX, bgY, bgX + bgW, bgY + 12, 0xD0202028);
                g.fill(bgX, bgY, bgX + bgW, bgY + 1, 0xFFD04848);   // top accent
                drawFlatCentered(g, inlineError, imageWidth / 2, bgY + 2, 0xFFFFB4B4);
            } else {
                inlineError = null;
            }
        }
    }

    /**
     * AE2 draws panel-surface text flat (no drop-shadow) so the character
     * glyphs read cleanly against the light-lavender chassis. Minecraft's
     * default {@link GuiGraphics#drawString(net.minecraft.client.gui.Font,
     * Component, int, int, int)} draws WITH a shadow, which on a light
     * panel produces an unpleasant embossed look. All label rendering in
     * this screen goes through this helper (and
     * {@link #drawFlatCentered}) to match AE2's native visual weight.
     */
    private void drawFlat(GuiGraphics g, Component text, int x, int y, int color) {
        g.drawString(font, text, x, y, color, false);
    }

    private void drawFlat(GuiGraphics g, String text, int x, int y, int color) {
        g.drawString(font, text, x, y, color, false);
    }

    private void drawFlatCentered(GuiGraphics g, Component text, int centerX, int y, int color) {
        int w = font.width(text);
        g.drawString(font, text, centerX - w / 2, y, color, false);
    }

    private void renderHomeLabels(GuiGraphics g) {
        // The AE2 info shelf backdrop is drawn in {@link #renderTabShelves}
        // (called from {@link #renderBg}), so buttons can overlay it and
        // text from this method is rendered AFTER the shelf. We only
        // deal with the label content here.
        int y = 24;
        var freq = ClientFrequencyCache.getFrequency(freqMenu().getCurrentFrequencyId());
        if (freq != null) {
            // Show the frequency's chosen RGB colour on its name so the
            // Home-tab readout matches the coloured row in the Selection
            // list. Fall back to ``DARK_AQUA`` styling via setStyle to
            // override any inherited colour.
            Component name = Component.literal(freq.name() + " (#" + freq.id() + ")")
                    .setStyle(Style.EMPTY.withColor(TextColor.fromRgb(freq.color() & 0xFFFFFF)));
            Component line = Component.translatable("ae2lt.gui.frequency.current")
                    .append(": ").append(name);
            drawFlat(g, line, 10, y, AE2_TEXT_BODY);
        } else {
            drawFlat(g, Component.translatable("ae2lt.gui.frequency.none"),
                    10, y, AE2_TEXT_MUTED);
        }
        y += 14;

        String deviceType = freqMenu().isController()
                ? (freqMenu().isAdvanced()
                        ? "block.ae2lt.advanced_wireless_overloaded_controller"
                        : "block.ae2lt.wireless_overloaded_controller")
                : "block.ae2lt.wireless_receiver";
        drawFlat(g, Component.translatable("ae2lt.gui.home.device_type")
                .append(": ").append(Component.translatable(deviceType)), 10, y, AE2_TEXT_BODY);
        y += 12;

        boolean connected = freqMenu().isLinkActive();
        drawFlat(g, Component.translatable("ae2lt.gui.home.status")
                        .append(": ")
                        .append(connected
                                ? Component.translatable("ae2lt.gui.home.connected").withStyle(ChatFormatting.DARK_GREEN)
                                : Component.translatable("ae2lt.gui.home.disconnected").withStyle(ChatFormatting.DARK_RED)),
                10, y, AE2_TEXT_BODY);
        y += 12;

        int used = freqMenu().getUsedChannels();
        int max = freqMenu().getMaxChannels();
        Component channelsValue;
        ChatFormatting color;
        if (max < 0) {
            channelsValue = Component.translatable("ae2lt.gui.home.grid_channels.infinite", used);
            color = ChatFormatting.DARK_AQUA;
        } else if (max == 0) {
            channelsValue = Component.translatable("ae2lt.gui.home.grid_channels.value", used, 0, 0);
            color = ChatFormatting.DARK_GRAY;
        } else {
            int remain = Math.max(0, max - used);
            channelsValue = Component.translatable("ae2lt.gui.home.grid_channels.value", used, max, remain);
            color = remain == 0 ? ChatFormatting.DARK_RED
                    : (remain * 4 < max ? ChatFormatting.GOLD : ChatFormatting.DARK_GREEN);
        }
        drawFlat(g, Component.translatable("ae2lt.gui.home.grid_channels")
                        .append(": ")
                        .append(channelsValue.copy().withStyle(color)),
                10, y, AE2_TEXT_BODY);
        y += 12;

        if (freqMenu().isController()) {
            drawFlat(g, Component.translatable("ae2lt.gui.home.cross_dimension")
                    .append(": ").append(freqMenu().isAdvanced()
                            ? Component.translatable("ae2lt.gui.home.cross_dimension.yes").withStyle(ChatFormatting.DARK_GREEN)
                            : Component.translatable("ae2lt.gui.home.cross_dimension.no").withStyle(ChatFormatting.DARK_RED)),
                    10, y, AE2_TEXT_BODY);
        }
    }

    private void renderSelectionLabels(GuiGraphics g) {
        // Single subtitle row between title (y=6) and shelf (y=28).
        // Text at y=18 renders glyphs on y=18..26, keeping a 2-px gap
        // above the shelf and well clear of the title descenders — the
        // two-row layout used previously overlapped the title at y=12.
        var freqs = ClientFrequencyCache.getAllFrequenciesSorted();
        var current = ClientFrequencyCache.getFrequency(freqMenu().getCurrentFrequencyId());

        Component left = Component.translatable("ae2lt.gui.frequency.current")
                .append(": ")
                .append(current != null
                        ? Component.literal(current.name()).setStyle(
                                Style.EMPTY.withColor(TextColor.fromRgb(current.color() & 0xFFFFFF)))
                        : Component.translatable("ae2lt.gui.frequency.none").withStyle(ChatFormatting.DARK_GRAY));
        drawFlat(g, left, 10, 18, AE2_TEXT_BODY);

        Component right = Component.translatable("ae2lt.gui.frequency.total").append(": " + freqs.size());
        drawFlat(g, right, imageWidth - 10 - font.width(right), 18, AE2_TEXT_MUTED);
        // No "password:" label here — the AETextField placeholder
        // communicates that already, and keeping the label out of the
        // shelf's bottom bevel avoids the prior clipping/overlap.
    }

    private void renderConnectionLabels(GuiGraphics g) {
        int currentId = freqMenu().getCurrentFrequencyId();
        if (currentId <= 0) {
            drawFlatCentered(g, Component.translatable("ae2lt.gui.error.no_frequency"),
                    imageWidth / 2, 40, AE2_TEXT_MUTED);
            return;
        }

        var conns = ClientFrequencyCache.getConnections(currentId);
        Component right = Component.translatable("ae2lt.gui.frequency.total")
                .append(": " + conns.size());
        drawFlat(g, right, imageWidth - 10 - font.width(right), 18, AE2_TEXT_MUTED);

        if (conns.isEmpty()) {
            drawFlatCentered(g, Component.translatable("ae2lt.gui.connection.none"),
                    imageWidth / 2, 70, AE2_TEXT_MUTED);
            return;
        }

        int start = connectionPage * ITEMS_PER_PAGE;
        int end = Math.min(start + ITEMS_PER_PAGE, conns.size());
        for (int i = start; i < end; i++) {
            var c = conns.get(i);
            int row = i - start;
            int y = 30 + row * 16;

            String typeKey = c.controller()
                    ? (c.advanced()
                            ? "block.ae2lt.advanced_wireless_overloaded_controller"
                            : "block.ae2lt.wireless_overloaded_controller")
                    : "block.ae2lt.wireless_receiver";
            ChatFormatting typeColor = c.controller() ? ChatFormatting.DARK_AQUA : ChatFormatting.DARK_GREEN;

            drawFlat(g, Component.translatable(typeKey).withStyle(typeColor),
                    8, y, AE2_TEXT_BODY);

            String posStr = "(" + c.pos().getX() + "," + c.pos().getY() + "," + c.pos().getZ() + ")";
            drawFlat(g, posStr, 8, y + 8, AE2_TEXT_MUTED);

            int dotColor = c.loaded() ? 0xFF3AA55A : 0xFF7F7F7F;
            g.fill(158, y + 2, 164, y + 8, dotColor);

            String dim = c.dimension();
            int slash = dim.indexOf(':');
            String shortDim = slash >= 0 ? dim.substring(slash + 1) : dim;
            if (shortDim.length() > 8) shortDim = shortDim.substring(0, 8);
            drawFlat(g, shortDim, imageWidth - 4 - font.width(shortDim), y + 8, AE2_TEXT_MUTED);
        }
    }

    private void renderMemberLabels(GuiGraphics g) {
        int currentId = freqMenu().getCurrentFrequencyId();
        if (currentId <= 0) {
            drawFlatCentered(g, Component.translatable("ae2lt.gui.error.no_frequency"),
                    imageWidth / 2, 40, AE2_TEXT_MUTED);
            return;
        }

        // Subtitle row — access on the left, count on the right, both at y=18.
        FrequencyAccessLevel myAccess = selfAccess();
        Component left = Component.translatable("ae2lt.gui.member.your_access",
                Component.translatable("ae2lt.gui.access." + myAccess.name().toLowerCase())
                        .withStyle(myAccess.getFormatting()));
        drawFlat(g, left, 10, 18, AE2_TEXT_BODY);

        var members = ClientFrequencyCache.getMembers(currentId);
        Component right = Component.translatable("ae2lt.gui.frequency.total")
                .append(": " + members.size());
        drawFlat(g, right, imageWidth - 10 - font.width(right), 18, AE2_TEXT_MUTED);

        if (members.isEmpty()) {
            drawFlatCentered(g, Component.translatable("ae2lt.gui.member.none"),
                    imageWidth / 2, 70, AE2_TEXT_MUTED);
        } else {
            drawFlatCentered(g, Component.translatable("ae2lt.gui.member.select_hint"),
                    imageWidth / 2, 140, AE2_TEXT_MUTED);
        }
    }

    private void renderCreateLabels(GuiGraphics g) {
        drawFlat(g, Component.translatable("ae2lt.gui.frequency.name").append(":"),
                16, 22, AE2_TEXT_MUTED);
        drawFlat(g, Component.translatable("ae2lt.gui.frequency.security").append(": "),
                16, 52, AE2_TEXT_MUTED);
        drawFlat(g, Component.translatable("ae2lt.gui.frequency.color").append(":"),
                16, 82, AE2_TEXT_MUTED);

        // Paint each preset-colour swatch on top of its vanilla Button.
        // The buttons are plain 14×14 gray cells registered in
        // {@link #initCreateTab}; this loop fills the 12×12 interior with
        // the actual preset colour so the user can tell them apart.
        // Coordinates here are LOCAL to the GUI (renderLabels' pose is
        // already translated to leftPos/topPos), which matches the local
        // offsets used when the buttons were positioned.
        for (int i = 0; i < PRESET_COLORS.length; i++) {
            int cx = 48 + (i % 7) * 16;
            int cy = 90 + (i / 7) * 16;
            int fill = PRESET_COLORS[i] | 0xFF000000;
            g.fill(cx + 1, cy + 1, cx + 13, cy + 13, fill);
            if (PRESET_COLORS[i] == editColor) {
                // Highlight the selected swatch with a 1-px white frame
                // so the user can see which colour they've picked.
                int accent = 0xFFFFFFFF;
                g.fill(cx,       cy,       cx + 14, cy + 1,  accent); // top
                g.fill(cx,       cy + 13,  cx + 14, cy + 14, accent); // bottom
                g.fill(cx,       cy,       cx + 1,  cy + 14, accent); // left
                g.fill(cx + 13,  cy,       cx + 14, cy + 14, accent); // right
            }
        }

        g.fill(16, 126, 28, 138, editColor | 0xFF000000);
        if (nameField != null && !nameField.getValue().isBlank()) {
            drawFlat(g, nameField.getValue(), 32, 128, editColor | 0xFF000000);
        }
    }

    private void renderSettingLabels(GuiGraphics g) {
        if (ClientFrequencyCache.getFrequency(freqMenu().getCurrentFrequencyId()) == null) {
            drawFlatCentered(g, Component.translatable("ae2lt.gui.error.no_frequency"),
                    imageWidth / 2, 40, AE2_TEXT_MUTED);
            return;
        }
        drawFlat(g, Component.translatable("ae2lt.gui.frequency.name").append(":"),
                16, 22, AE2_TEXT_MUTED);
        drawFlat(g, Component.translatable("ae2lt.gui.frequency.security").append(": "),
                16, 52, AE2_TEXT_MUTED);
    }

    private static Component getSecurityLabel(FrequencySecurityLevel level) {
        return switch (level) {
            case PUBLIC -> Component.translatable("ae2lt.gui.security.public");
            case ENCRYPTED -> Component.translatable("ae2lt.gui.security.encrypted");
            case PRIVATE -> Component.translatable("ae2lt.gui.security.private");
        };
    }

    @Override
    public void render(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
        renderBackground(g, mouseX, mouseY, partialTick);
        super.render(g, mouseX, mouseY, partialTick);
        renderTooltip(g, mouseX, mouseY);
    }

    // Helpers

    private boolean isSelf(UUID uuid) {
        var mc = Minecraft.getInstance();
        return mc.player != null && mc.player.getUUID().equals(uuid);
    }

    private FrequencyAccessLevel selfAccess() {
        var members = ClientFrequencyCache.getMembers(freqMenu().getCurrentFrequencyId());
        var mc = Minecraft.getInstance();
        if (mc.player == null) return FrequencyAccessLevel.BLOCKED;
        UUID me = mc.player.getUUID();
        for (var m : members) {
            if (m.uuid().equals(me)) return m.access();
        }
        // fall back to frequency security: PUBLIC → USER, else BLOCKED
        var freq = ClientFrequencyCache.getFrequency(freqMenu().getCurrentFrequencyId());
        if (freq != null && freq.security() == FrequencySecurityLevel.PUBLIC) {
            return FrequencyAccessLevel.USER;
        }
        return FrequencyAccessLevel.BLOCKED;
    }

    private boolean hasManagerAccess() {
        return selfAccess().isManager();
    }

    private boolean hasOwnerAccess() {
        return selfAccess().isOwner();
    }

    private static String accessShort(FrequencyAccessLevel a) {
        return switch (a) {
            case OWNER -> "O";
            case ADMIN -> "A";
            case USER -> "U";
            case BLOCKED -> "B";
        };
    }

}
